### ISSUE TITLE
Tiefspanner

### ISSUE THREAD

**Issue by thomaslusli** [christiankral/Grundlagen-der-Antriebstechnik#12]
Tippfehler bei : "Beim Tiefspanner mit U2 < **U1** ...:" auf Seite 151

**Comment by christiankral** [comment]
Danke für den Hinweis. Der Fehler ist für die nächste Auflage korrigiert: 

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/e325b5b9-3fa1-4d50-9832-d19276ad6f69)
