### ISSUE TITLE
Inkonsistenz I_S und I_1 in Ersatzschaltbildern Stator

### ISSUE THREAD

**Issue by markusforsterhtlwy** [christiankral/Grundlagen-der-Antriebstechnik#16]
Bild 10.6b hat den Strom I_S **rechts** vom Eisenverlustwiderstand
Kapitel 11 hat I_S **links** vom Eisenverlustwiderstand
Kapitel 12 hat I_S wieder **rechts** vom Eisenverlustwiderstand

Übersehe ich wo die Begründung, warum das bei der Asynchronmaschine umgekehrt ist?

**Comment by christiankral** [comment]
Danke @markusforsterhtlwy für den Hinweis. Die ursprüngliche geplante Vereinheitlichung der Bilder und Bezeichnungen ist an mehreren Stellen schief gegangen.

Die Bezeichnung in Bild 10.6b ist FALSCH:

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/1ee8a249-9ef9-4f8e-95a1-6b28a09b8d3a)

Die beabsichtigte Bezeichnung ist wie etwa in Bild 11.9

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/0bb68195-74e8-4a46-b7dc-6e8b4fecff24)

Auch die Bezeichnung, wie in Bild 12.14, ist daher leider falsch. 

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/8f324236-2854-42e9-8611-1e5f3c179da1)

Dass es zwei Darstellungsformen gibt ist einer fehlerhaften Vereinheitlichung der Bilder zuzuschreiben, die ich zwar durchführen wollte, aber leider nicht korrekt durchgeführt habe. In der Liste der Formelzeichen auf Seite 351 sind die Ströme korrekt bezeichnet, aber die Formelzeichen $\underline I_s$ und $\underline I_1$ sind nachfolgend trotzdem falsch verwendet.

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/b075736d-6c6b-4acb-afd0-682f6b5acbde)

Die Gleichungen (12.6), (12.8), (12.11) und (12.13) sind nicht korrekt. 

Ab Abschnitt 12.2.4 wird mit dem vereinfachten Ersatzschaltbild unter Berücksichtigung von $\underline I_s \approx \underline I_1$ gerechnet -- dann ist die Welt wieder in Ordnung.

Ich ergänze das in den [Errata](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/blob/main/Errata/Errata-Grundlagen-der-Antriebstechnik-Auflage-1.pdf)

**Comment by christiankral** [comment]
Als Konseuquenz ist außerdem Gl. (11.13) falsch.

**Comment by christiankral** [comment]
Hoffentlich sind jetzt alle damit einhergehenden Unstimmigkeiten korrigiert, siehe [Errata](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/blob/main/Errata/Errata-Grundlagen-der-Antriebstechnik-Auflage-1.pdf)

**Comment by christiankral** [comment]
Ich denke soweit ist jetzt mal alles korrigiert.

@markusforsterhtlwy Bitte Issue erneut öffnen, falls zu diesem Thema weitere Fehler auffallen. Danke.

**Comment by markusforsterhtlwy** [comment]
@christiankral: Danke, jetzt ist alles schlüssig.
