### ISSUE TITLE
Letto-Beispiel 11.2.4 Typenschild Bemessungsdaten 1

### ISSUE THREAD

**Issue by markusforsterhtlwy** [christiankral/Grundlagen-der-Antriebstechnik#18]
Bei diesem Beispiel wird der Schlupf im Datensatz vorgegeben. Die mechanische Drehzahl wird dann mit Maxima via Polpaarzahl und Statornennfrequenz berechnet und **GERUNDET**.

Die Schüler rechnen dann mit diesem gerundeten Nenndrehzahl den Schlupf aus und erhalten natürlich eine Abweichung vom vorgegebenen Schlupf.

**Empfehlung:** Schlupfergebnis in Maxima mit gerundeter Drehzahl berechnen und diese berechnete Größe für den Vergleich mit der Eingabe verwenden.

**Comment by christiankral** [comment]
Danke für den Hinweis. 

Ja, es ist erforderlich, den Schlupf mit der konkret angegebenen Drehzahl zu ermitteln:

```maxima
UYN : ground(UDN * sqrt(3),2)
IDN : ground(IYN * sqrt(3),2)

SN : 3 * UDN * IYN
PmN : ground(SN * pfN * etaApprox,3)
nN : ground(fsN / p * (1 - sN),3)
MN : PmN / (2*%pi*nN)
etaN : PmN / (SN * pfN)
// sN aus Datensatz mit gerundetem Rechenwert überschreiben
sN : fsN / p / nN - 1 
```

**Comment by christiankral** [comment]
LTO-Datei und Online-Beispielsammlung aktualisiert.
