### ISSUE TITLE
5.4.4 Leistungsbilanz und Wirkungsgrad

### ISSUE THREAD

**Issue by norbertschwarz** [christiankral/Grundlagen-der-Antriebstechnik#19]
Sehr geehrter Herr Kral!

Beim nachfolgenden Beispiel gibt es nicht mehr den Link zu den Katalogdaten, somit kann das Beispiel nicht mehr bearbeitet werden.

![image](https://github.com/user-attachments/assets/ccae16be-6273-4d9c-809e-8cc69f12060c)

SG, Norbert Schwarz

**Comment by christiankral** [comment]
@norbertschwarz Das ist dasselbe Problem wie in https://github.com/christiankral/Grundlagen-der-Elektrotechnik/issues/1

Die Katalogdaten sind ebenso wie Bilder in der LTO-Datei hinterlegt. Nach einem Update der LeTTo-Version sollte der Import korrekt funktionieren.

**Comment by norbertschwarz** [comment]
@christiankral Das kann ich so nicht ganz nachvollziehen, da auf Ihrer LeTTo- Version das gleiche Problem ist --> Siehe unten!

![image](https://github.com/user-attachments/assets/a1761323-c8ea-4aad-b512-93f346777ca2)

SG, Norbert Schwarz

**Comment by christiankral** [comment]
@norbertschwarz Mein Fehler. Ich hatte in Erinnerung, dass die Katalogdaten als interne Datei hinterlegt sind. Das war in der aktuellen Version nicht mehr der Fall. Stattdessen wurde auf eine externe Datei von ABB verlinkt. Dieser Link existiert jedoch mittlerweile nicht mehr. Daher habe ich wieder auf eine interne verlinkte Datei umgestellt.

**Comment by norbertschwarz** [comment]
@christiankral Herzlichen Dank für die Information und die Bemühungen.

**Comment by christiankral** [comment]
@norbertschwarz Leider hat der Export auf den Server https://s5.letto.at/ nicht funktioniert. Ich bespreche das Problem mit @l-mayt für eine zeitnahe Lösung.

**Comment by norbertschwarz** [comment]
@christiankral Ja habe es gerade getestet und funktioniert leider nicht. Wie ich sehe hat der Server https://s5.letto.at/ eine wesentlich höhere Rev. als unser Server. --> 

![image](https://github.com/user-attachments/assets/298e9877-0f48-4e35-9ba6-965bee6d18b5)

![image](https://github.com/user-attachments/assets/5b325459-5fc1-439c-b85a-6b083687994a)

Zudem musste ich feststellen, dass es scheinbar den Benutzer "user" mit dem dazugehörigen Passwort nicht mehr gibt. Wurde das jetzt bewusst geändert. War zumindest noch vor einigen Monaten frei zugänglich!

**Comment by christiankral** [comment]
> @christiankral Ja habe es gerade getestet und funktioniert leider nicht. Wie ich sehe hat der Server https://s5.letto.at/ eine wesentlich höhere Rev. als unser Server. -->

Das Problem mit dem Server https://s5.letto.at ist auf https://project.letto.at/projects/letto/work_packages/1909/ dokumentiert und wird in recht absehbarer Zeit behoben sein. Ich gebe eine entsprechende Rückmeldung, sobald alles wieder funktioniert.

**Comment by christiankral** [comment]
OK, die Fragen am Server https://s5.letto.at/kral/open funktionieren wieder. Es gibt derzeit noch ein Problem mit den Umlauten in den Fragenamen, aber das wird in absehbarer Zeit behoben sein.

**Comment by norbertschwarz** [comment]
@christiankral Danke - heißt der Zugriff zum externen Fragenservice über den LeTTo-Server  https://s5.letto.at/ mittels dem Benutzer: user gibt es auch nach wie vor, nur gibt es da ein internes Problem.

**Comment by christiankral** [comment]
> Der Benutzer user wurde scheinbar gelöscht oder geändert.........

Nach Rückfrage bei @l-mayt: Das ist korrekt. Diesen User gibt es nicht mehr. Die aktuelle LeTTo-Version ermöglicht allerdings die direkt Einbindung von Fragen des Exchange-Servers:

![image](https://github.com/user-attachments/assets/94fb37b1-a29a-40a2-8cb4-9859ad854a12)

**Comment by norbertschwarz** [comment]
@christiankral Herzlichen Dank - leider habe ich nicht die aktuelle Version und somit habe ich keine Möglichkeit auf einen Zugriff auf den Exchange Server - das finde ich sehr schade. Sehe da hat sich einiges getan. Wäre es möglich einen zeitlich befristeten Gastzugang zu erhalten? Danke.

**Comment by christiankral** [comment]
> Wäre es möglich einen zeitlich befristeten Gastzugang zu erhalten?

@norbertschwarz Dazu müssten Sie sich bitte an die LeTTo-Entwickler wenden.

Darf ich fragen an welcher Schule sie sind? Ich denke die sinnvollste Lösung ist, dass ihr LeTTo-Adminstrator ein Update des LeTTo-Servers durchführt. 

Wie ich es verstanden habe, gibt es voraussichtlich diese oder nächste Woche eine neue Stable-Version, die von allen Bildungseinrichtungen ab dann verwendet werden sollte. 

Wir arbeiten am TGM derzeit mit einer Daily-Version, die ebenfalls recht stabil läuft. Vielleicht können Sie ihren LeTTo-Administrator dazu bringen, vorläufig die Daily-Version und nach dem Release der Stable-Version ein erneutes Update durchzuführen.

**Comment by norbertschwarz** [comment]
@christiankral Sorry für die verspätete Nachricht, hatte das Notebook nicht dabei. Zu Ihrer Frage - arbeite an der HTL Mössinger in Klagenfurt. Mhh bin dann neugierig wie das bei uns mit der neuen Version klappt. Jedenfalls danke für die Information.

**Comment by christiankral** [comment]
@norbertschwarz Ich denke das Hauptproblem dieses Tickets sollte jetzt gelöst sein. Ich schließe daher dieses Ticket. Falls etwas von diesem Issue noch nicht erledigt sein sollte, bitte erneut öffnen.
