### ISSUE TITLE
Tippfehler in Einheit in Beispiel Physikalische Einheiten (157662978) in Kapitel 0

### ISSUE THREAD

**Issue by markusforsterhtlwy** [christiankral/Grundlagen-der-Antriebstechnik#2]
In der Zelle "Drehzahl / Schreibweise" wird die Einheit mit "Ump" angegeben. Soll auf "Upm" ausgebessert werden.

**Comment by christiankral** [comment]
Danke für den Hinweis.

Ich habe eine aktuelle Version der LTO-Datei über 58c0c25cb46966e54db4def223d3f1541fc370c7 hochgeladen. Auf dem Server https://s5.letto.at/kral/open steht die Aktualisierung derzeit noch aus, aber folgt demnächst.

**Comment by christiankral** [comment]
Aktualisierung auf dem Server https://s5.letto.at/kral/open durchgeführt.
