### ISSUE TITLE
Lieber Herr Kral - Seite 355 - Tab. 12.1 --> Die Beschriftung ist nicht korrekt 

### ISSUE THREAD

**Issue by l-asch** [christiankral/Grundlagen-der-Antriebstechnik#20]
Die Beschriftung bezieht sich auf die ASM und das im SM Kapitel

**Comment by christiankral** [comment]
@l-asch Danke für den Hinweis. Die Korrektur dieses Fehlers ist für die Neuauflage und in den [Errata](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/blob/main/Errata/Errata-Grundlagen-der-Antriebstechnik-Auflage-1.pdf) berücksichtigt.
