### ISSUE TITLE
7.1.5 Erregerwicklung Richtung zweipolig

### ISSUE THREAD

**Issue by norbertschwarz** [christiankral/Grundlagen-der-Antriebstechnik#21]
![image](https://github.com/user-attachments/assets/c8621742-dbdb-414c-8c12-2dc984c7380c)

Sehr geehrter Herr Kral!

Das Beispiel ist fehlerhaft, leider finde ich selbst in der Implementierung auch nicht den Fehler.

Vielleicht könnten Sie sich das Beispiel ansehen. Herzlichen Dank! SG, Norbert Schwarz

**Comment by christiankral** [comment]
@norbertschwarz  Was funktioniert aus Ihrer Sicht nicht? Wenn ich das Beispiel auf unserem Server teste, funktioniert es:

![image](https://github.com/user-attachments/assets/461693e7-c0f1-44f9-b7ab-5c576a79412d)

Korrigiert habe ich den Namen der Aufgabe "... Richung ..." => "... Rich**t**ung ..."

**Comment by norbertschwarz** [comment]
@christiankral Sehr geehrter Herr Krall! Wenn Sie die diversen Datensätze durchspielen, dann erkennen Sie, dass einzelne Datensätze nicht die richtige Antwort liefern. Siehe angehängtes Bild. SG, Norbert Schwarz
![image](https://github.com/user-attachments/assets/35097b7a-3f31-40c3-8a49-3a466a592875)

**Comment by christiankral** [comment]
@norbertschwarz  Es gibt insgesamt vier unterschiedliche Datensätze in dieser Aufgabe. Ich habe alle vier Datensätze getestet. Sie funktionieren in der LeTTo-Version 

![image](https://github.com/user-attachments/assets/572e0ee0-a3f5-48b3-95e0-d35ad4966de2)

unserer Schule:

![image](https://github.com/user-attachments/assets/ce682eaa-98dd-45db-8ddf-aad9fefc77e8)
 
Ich erinnere mich, dass es vor einigen Wochen Probleme mit einer LeTTo-Version gab, bei der die falschen Lösungen geprüft wurden:

https://project.letto.at/projects/letto/work_packages/1975/
https://project.letto.at/projects/letto/work_packages/2005/

@l-mayt Ich vermute, dass ein Update auf eine aktuelle LeTTo-Version das Problem lösen könnte.

**Comment by norbertschwarz** [comment]
@christiankral Sehr geehrter Herr Krall!

Ich konnte den Fehler finden.
![image](https://github.com/user-attachments/assets/e8e2d5f7-3d24-4bbb-9d7c-5f8ebf7e31f3)
Wenn Vorberechnung und Parser aktiviert ist, dann ist das Beispiel fehlerhaft. Ist lediglich Parser aktiviert funktioniert das Beispiel einwandfrei.
Ich selbst habe die Rev. 6642 in Verwendung, also doch eine sehr aktuelle Version.
Herzlichen Dank für Ihre Bemühungen! SG, Norbert Schwarz

**Comment by christiankral** [comment]
@norbertschwarz  Ich bin grundsätzlich froh, dass das Beispiel bei Ihnen nun funktioniert. 

@damboeck Ich verstehe allerdings nicht, warum man die Vorausberechnung ausschalten müsste. Ich kann das auch gar nicht reproduzieren. Bei mir funktioniert es mit und ohne Häkchen bei der Vorausberechnung.

**Comment by norbertschwarz** [comment]
@christiankral 
@damboeck

Sehr geehrte Herren!
Ich habe das nochmals verifiziert, wenn ich Vorberechnung und Parser auswähle erfolgte eine falsche Berechnung. Wenn lediglich Parser ausgewählt ist erfolgt eine korrekte Darstellung der diversen Datensätze. Ich arbeite mit der Rev. 6642. Kann dies sonst gerne auch online über ein Meeting vorführen.
SG, Norbert Schwarz

**Comment by christiankral** [comment]
@norbertschwarz  Bedeutet falsche Berechnung:
a) Eine falsche Lösung wird als korrekt gewertet
b) Keine Lösung ist korrekt

**Comment by christiankral** [comment]
@norbertschwarz Was zeigt die "Anzeige von allen Datensätzen und allen Ergebnissen" in LeTTo, wenn die Vorausberechnung nicht angehakt ist, d. h. die falsche Berechnung durchgeführt wird?

Bei mir zeigt dieser Button am TGM-Server mit derselben LeTTo-Revision-Nummer unabhängig davon, ob ich Vorausberechnung angehakt habe, oder nicht, folgendes Bild:

![image](https://github.com/user-attachments/assets/c826dd44-4ce9-40ea-912d-cbb5ca750164)

**Comment by norbertschwarz** [comment]
@christiankral 
@damboeck

Bei mir zeigt es folgende Datensätze an - der nachfolgende ist korrekt --> ohne Vorberechnung !!!!

![image](https://github.com/user-attachments/assets/d90529ca-e8b4-4003-af83-24658d9f476c)

Nunmehr mit Vorberechnung:

![image](https://github.com/user-attachments/assets/5413d918-06b6-4dd8-8d29-acb4561a694f)

Datensatz sieht gleich aus - trotzdem wird das Ergebnis falsch angezeigt!!!! Siehe nachfolgendes Bild:

![image](https://github.com/user-attachments/assets/0cfc816c-813d-49ef-977f-fc01eb06e840)

Wenn ich den Haken bei Vorberechnung entferne passt die Lösung:

![image](https://github.com/user-attachments/assets/7b2704e0-1c1b-43ae-8267-46eb9a3f9adc)

Ich kann auch nur das so wiedergeben, wie sich die IST- Situation darstellt.

SG, Norbert Schwarz

**Comment by christiankral** [comment]
Die Aufgabe hatte offenbar Probleme mit der Reihenfolge der Bilder, die im Plot-Plugin verwendet wird. Da ist etwas durcheinandergeraten, was ich nicht nachvollziehen kann, da ich die Reihenfolge sicher nicht geändert habe. Zur Lösung dieses Problems habe ich die Reihenfolge der Bilder neu angeordnet und den Maxima-Code entsprechend angepasst. Aus meiner Sicht sollte das Problem jetzt gelöst ein.

@norbertschwarz Ich bitte Sie die [überarbeitete Aufgabe](https://github.com/user-attachments/files/18163054/Frage_Erregerwicklung_Richtung_zweipolig.lto.zip)  bei Ihnen zu testen. Sie sollte jetzt mit und ohne Vorausberechnung funktionieren.

Das Beispiel funktioniert jetzt auch auf https://s5.letto.at/kral/open

![image](https://github.com/user-attachments/assets/802444ce-eb16-4da3-bfb4-d7fdb5e23072)

**Comment by christiankral** [comment]
@norbertschwarz Ich lasse die Aufgabe noch offen und warte auf Ihr Feedback.

**Comment by norbertschwarz** [comment]
@christiankral Das Beispiel funktioniert mit sämtlichen Datensätzen korrekt. Herzlichen Dank für Ihre Bemühungen. Ich wünsche Ihnen ein schönes Weihnachtsfest und einen guten Rutsch ins neue Jahr. SG, Norbert Schwarz

**Comment by christiankral** [comment]
@norbertschwarz Gut, dass jetzt die Aufgabe funktioniert.

Ich wünsche auch Ihnen frohe Festtage und alles Gute für das Neue Jahr 2025.
