### ISSUE TITLE
Beispiel 12.1.4 Permanentmagnetläufer Pole N

### ISSUE THREAD

**Issue by markusforsterhtlwy** [christiankral/Grundlagen-der-Antriebstechnik#3]
Beispiel wird in https://s5.letto.at/kral/open nicht korrekt ausgewertet.
Aufgabe benötigt in lokalem Letto-Import zuerst eine Maxima-Berechnung. Dann läuft es.

**Comment by christiankral** [comment]
Danke für den Hinweis. Die Online-Version dieser Frage auf https://s5.letto.at/kral/open funktioniert nun ebenfalls
