### ISSUE TITLE
Frage zur Aufgabe "Idealer Transformator"

### ISSUE THREAD

**Issue by moreno0602** [christiankral/Grundlagen-der-Antriebstechnik#5]
Ich bin momentan im Kapitel Einphasen Transformator. Dazu habe ich folgende Übungsaufgabe gemacht und von Hand gerechnet. Die Frage, die sich mir stellt ist folgende: 

Gegeben ist ein idealer Transformator mit n_12=13.
Der Transformator wird auf der Seite 1 mit  
U_1 =500V∠80° versorgt und auf der Seite mit dem Widerstand R_2=9.6Ω belastet. 

- Wieso hat der Strom in der Lösung eine Phasenverschiebung von -100° ??
Ich habe zuerst die Spannung der Seite 2 berechnet, was ja 500V / 13 = 38.462V sind. Der Phasenwinkel ist ja derselbe. Dann habe ich ja einen Widerstand von 9.6Ω.
Das heißt ja 38.462V/9.6Ω = 4.006A aber müsste hier der Phasenwinkel nicht auch 80° betragen? Wie kommt man hier auf -100°??

Danke im Voraus.

**Comment by christiankral** [comment]
Der Schlüssel zur Antwort liegt in der Orientierung des Stroms $\underline I_2$. 

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/30dd49fd-78ec-4a67-9210-54a03586df59)

Das Ohmsche Gesetz lautet für den Lastwiderstand: 

$\underline U_2 = - R_2 \cdot \underline I_2$

Das negative Vorzeichen rührt daher, dass der Strom $\underline I_2$ und die Spannung $\underline U_2$ nicht die gleiche Richtung aufwiesen -- siehe dazu Tabelle 1.2.

Damit ergibt sich $\underline I_2 = -\dfrac{\underline U_2}{R_2} = (\underbrace{1\angle 180°}_{-1}) \cdot \dfrac{500~\mathrm{V}\angle 80°}{9.6 \Omega} = 4.064 \mathrm{A}\angle -100°$

Die Gl. (5.7) ergibt damit für den Strom auf der Seite 1:

$\underline I_1 = -\dfrac{\underline I_1}{n_{12}} = (1\angle 180°)\cdot\dfrac{4.064\mathrm{A}\angle-100°}{13}=308.2\mathrm{mA}\angle80°$

**Comment by christiankral** [comment]
@moreno0602 Dieses Beispiel ist nun mit einer Hilfe (Feedback) versehen:

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/9190f2fb-83c4-4e33-b459-35f706de213c)

Darin sind die erwähnten Hinweise hinterlegt:

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/dbc4af79-6eca-4c38-9bf6-1f2006f7d9f2)
