### ISSUE TITLE
Diverse Fragen 

### ISSUE THREAD

**Issue by NixieWatchman** [christiankral/Grundlagen-der-Antriebstechnik#7]
- [x] 1.7.1 Ventil sperrt--> Wieso ist der Strom kleiner 0? Kriechströme sind doch eher größer 0... oder geht es hier um Ströme in Freilaufdioden, Bodydioden usw.?

- [x] 3.3.1 Reibungsverluste--> Rechnerisch nehmen die Luftreibungsverluste natürlich mit der dritten Potenz mit der Drehzahl an. Der Aufbau des Lüfters einer Maschine ist jedoch oft sehr simpel und robust mit geraden Rotorblättern (ohne Verdrehung) ausgeführt. Führt dies in Realität bei Umdrehungszahlen von z.B. n=3000 Upm nicht dazu, dass die Rotorblätter gegenseitig eine Art "Windschatten" und starke Verwirbelungen erzeugen und würde dadurch der Anstieg des Luftwiderstands nicht stark gesenkt werden? (Deshalb kann man ja auch WKA mit hohen Rotorblattzahlen nur als Langsamläufer und nur bei recht geringem Leistungsfaktor ausführen)

- [x] 6.7.4 Wieso kann mit einem Längsregler nur Q und mit Quer- oder Schrägregler P anpassen? Weil man durch Quer- und Schrägregler \phi anpasst?

- [x] 7.3.6 Wann ist U_{i}'=(R_{a}+R_{e})\cdot I_{e}' nicht erfüllt? Gibt es weitere Komponenten in der Gleichung die im Hochlauf für eine Ungleichheit der beiden Seiten von (7.41) sorgen oder kommt die Ungleichheit durch die Remanenzspannung zustand, welche keinen Stromfluss bewirkt? Bzw. wie kommt Gl. (7.41) überhaupt zustande? Ich bin etwas verwirrt von der Bedeutung der Formel, da der reine Aufbau der Gleichung impliziert, dass Ra und Re in gewisser weise in Serie geschaltet sind aber dabei sind sie eben parallel. Oder geht es hier um den Zeitpunkt in dem die Ankerklemmen noch im Leerlauf sind?  

- [x] 11.8 Wird die Drehzahl einer doppelt gespeisten Asynchronmaschine negativ wenn fr>fs? Also führt dies zu einer allgemeinen Drehrichtungsänderung? Oder kann fr>fs nur im generatorischen Betrieb auftreten? Wird im übersynchronen Betrieb für fr<0Hz eine Phasenverschiebung von 180° eingeprägt oder werden die Phasen durch die Elektronik im Umrichter Vertauscht, sodass ein Link- statt einem Rechtsdrehfeld entsteht?

Mfg Alexander Prohaska

**Comment by christiankral** [comment]
> 1.7.1 Ventil sperrt--> Wieso ist der Strom kleiner 0? Kriechströme sind doch eher größer 0... oder geht es hier um Ströme in Freilaufdioden, Bodydioden usw.?

Im Prinzip kommt es auf die Modellvorstellung an. Wenn man die Vorwärts-Flussspannung nicht berücksichtigt:

![Kennlinien](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/7be2f610-3e39-4858-a0c3-41afee75f912)

- Grün: vorwärts leiten mit kleinem positiven Spannungsabfall
- Rot: rückwärts sperren mit kleinem negativen Strom

**Comment by christiankral** [comment]
> 3.3.1 Reibungsverluste--> Rechnerisch nehmen die Luftreibungsverluste natürlich mit der dritten Potenz mit der Drehzahl an. Der Aufbau des Lüfters einer Maschine ist jedoch oft sehr simpel und robust mit geraden Rotorblättern (ohne Verdrehung) ausgeführt. Führt dies in Realität bei Umdrehungszahlen von z.B. n=3000 Upm nicht dazu, dass die Rotorblätter gegenseitig eine Art "Windschatten" und starke Verwirbelungen erzeugen und würde dadurch der Anstieg des Luftwiderstands nicht stark gesenkt werden? (Deshalb kann man ja auch WKA mit hohen Rotorblattzahlen nur als Langsamläufer und nur bei recht geringem Leistungsfaktor ausführen)

Korrekt: In der Praxis rechnet mit dem Reibungsmoment proportial zu einem Exponenten zwischen 1 und 2, woraus sich für die Reibungsleistung ein Exponent zwischen 2 und 3 ergibt. Dazu aus meinen Modelica-Buch:

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/59ddf082-7625-4344-bf54-cf968759b1de)

**Comment by christiankral** [comment]
> 6.7.4 Wieso kann mit einem Längsregler nur Q und mit Quer- oder Schrägregler P anpassen? Weil man durch Quer- und Schrägregler \phi anpasst?

Der Schlüssel dazu, welche Leistungsanteile beeinflusst werden können, liegt im (vereinfacht) gewählten Ersatzschaltbild:

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/e6e96dcd-a63a-43e4-9c5f-1eaf426e6e00)

Man kann sich vorstellen, dass die Spannung $\Delta \underline U_1$ im Sinne einer Superposition einen Kreisstrom (Maschenstrom) über die Reaktanzen $X_1$ und $X_{1p}$ treibt. Der Strom $\underline I_1$ durch die Reaktanz $X_1$ eilt der Spannung $\Delta \underline U_1$ aufgrund ihres induktivien Charakters immer um 90° nach:

- Bild 6.18a: Wenn $\Delta \underline U_1$ in Phase mit $\underline U_1$ ist, dann eilt der Strom $I_1$ auch der Spannung $U_1$ um 90° nach => Blindleistung
- Bild 6.18b:  Wenn $\Delta \underline U_1$ der Spannung $\underline U_1$ um 90° nacheilt, dann ist der Strom $I_1$ in Gegenphase (180°) mit $U_1$ => Wirkleistung
- Mit unterschiedlichen Phasenwinkeln zwischen $\Delta \underline U_1$ und $\underline U_1$ beeinflusst man immer Wirk- und Blindleistung gemeinsam

**Comment by christiankral** [comment]
> 7.3.6 Wann ist U_{i}'=(R_{a}+R_{e})\cdot I_{e}' nicht erfüllt? Gibt es weitere Komponenten in der Gleichung die im Hochlauf für eine Ungleichheit der beiden Seiten von (7.41) sorgen oder kommt die Ungleichheit durch die Remanenzspannung zustand, welche keinen Stromfluss bewirkt? Bzw. wie kommt Gl. (7.41) überhaupt zustande? 

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/1ab3be70-d740-47fd-9cc7-ec4260c18dfc)

Gleichung (7.41) ist im stationären Betrieb eine Konsequenz aus $U_a = R_a \cdot I_a + U_i$ und $U_a = R_e \cdot I_e = R_e \cdot I_a$ für $I_L=0$, indem man $U_a$ eliminiert. 

> Ich bin etwas verwirrt von der Bedeutung der Formel, da der reine Aufbau der Gleichung impliziert, dass Ra und Re in gewisser weise in Serie geschaltet sind aber dabei sind sie eben parallel. Oder geht es hier um den Zeitpunkt in dem die Ankerklemmen noch im Leerlauf sind?

Tatsächlich gilt für $I_L = 0$ dass $I_a = -I_e$ ist und das entspricht aus Sicht der inneren Spannung einer Serienschaltung von Anker- und Erregerkreis.

Während des Selbsterregungsvorgangs wirken auch die Induktivitäten des Ankers ($L_a$) und des Erregerkreises ($L_e$). Aus Gl. (7.8) folgt:

$U_{i}=(R_{a}+R_{e})\cdot I_{e} + (L_a + L_e) \cdot \dfrac{\text d I_a}{\text d t}$

Daher gilt Gl. (7.41) nur im stationären Fall.

**Comment by christiankral** [comment]
> 11.8 Wird die Drehzahl einer doppelt gespeisten Asynchronmaschine negativ wenn fr>fs? Also führt dies zu einer allgemeinen Drehrichtungsänderung? Oder kann fr>fs nur im generatorischen Betrieb auftreten? Wird im übersynchronen Betrieb für fr<0Hz eine Phasenverschiebung von 180° eingeprägt oder werden die Phasen durch die Elektronik im Umrichter Vertauscht, sodass ein Link- statt einem Rechtsdrehfeld entsteht?

Es gilt allgemein Gl. (11.82):

![image](https://github.com/christiankral/Grundlagen-der-Antriebstechnik/assets/4184218/66c47512-1a27-4508-9542-4afb5048037e)

- Untersynchron bedeutet, dass $n < f_s / p$ ist, daher ist $f_r > 0$ => Drehfeldrichtung gleich wie im Stator
- Übersynchron bedeutet, dass $n > f_s / p$ ist, daher ist $f_r < 0$ => Drehfeldrichtung anders als im Stator => entspricht einem vertauschen Ansteuerung zweier Phasen

**Comment by christiankral** [comment]
@NixieWatchman Ticket bitte schließen, falls alles zufriedenstellend beantwortet ist. Andernfalls bitte neue Kommentare hinzufügen.

**Comment by christiankral** [comment]
@NixieWatchman Ich schließe dieses Ticket mal. Falls noch etwas behandelt werden muss, bitte erneut öffnen oder ein neues Ticket anlegen.
