### ISSUE TITLE
Formelzeichen der Winkelgeschwindigkeit

### ISSUE THREAD

**Issue by LieblingKreuzberg** [christiankral/Grundlagen-der-Antriebstechnik#8]
Ich bin es gewohnt, die Winkelgeschwindigkeit mit einem kleinen $\omega$ zu bezeichnen. Das große $\Omega$ kennzeichnet (bei uns Elektronikern:-) ) die normierte Kreisfrequenz. Kreisfrequenz und Winkelgeschwindigkeit bezeichnen das gleiche, einmal elektrisch und einmal mechanisch betrachtet. Meine Ausbildung in den elektrischen Maschinen ist halt schon lange her:-)

LG, Andreas.

**Comment by christiankral** [comment]
Es gab habe zwei Möglichkeiten überlegt, die Winkelgeschwindigkeit und die Kreisfrequenz zu unterscheiden. 

1. In Anlehnung an *Hanskarl Eckhardt, "Grundzüge der elektrischen Maschinen", B. G. Teubner Stuttgart 1982*, habe ich mich entschlossen die mechanische Winkelgeschwindigkeit mit $\Omega$ und die elektrische Kreisfrequenz mit $\omega$ zu bezeichnen. Damit gilt (mit der Polpaarzahl $p$): $\omega = p \cdot \Omega$
2. Alternativ könnte man die mechanische Winkelgeschwindigkeit mit einem zusätzlichen Index (beispielsweise $m$) kennzeichnen. In diesem Fall hätten wir: $\omega = p \cdot \omega_m$

Ich habe mich für die Variante 1 entscheiden, da man sonst leichter versucht ist, den Index $m$ -- etwas bei der Gleichstrommaschine -- fortzulassen, da es ohnehin keine elektrische Kreisfrequenz gibt. Das würde später dann bei den Drehfeldmaschinen jedoch zu Widersprüchen führen ...
